#  hypr/.config/hypr/custom/index.conf

source = ~/.config/hypr/custom/unbindings.conf
source = ~/.config/hypr/custom/bindings.conf
source = ~/.config/hypr/custom/hyprland.conf
source = ~/.config/hypr/custom/monitors.conf
source = ~/.config/hypr/custom/workspace.conf
source = ~/.config/hypr/custom/layout.conf
source = ~/.config/hypr/custom/plugins.conf
source = ~/.config/hypr/custom/scrolling.conf
# source = ~/.config/hypr/hypridle.conf

source = ~/.config/hypr/custom/input.conf





