# Запуск демона
exec-once = sleep 10 && pypr

# --- ГЛАВНОЕ ПРАВИЛО ---
windowrule = float on, match:initial_title ^(scratch-[uilhm])$
windowrule = center on, match:initial_title ^(scratch-[uilhm])$

# --- ПРИВЯЗКА К WORKSPACE ---
windowrule = workspace special:scratch_u silent, match:initial_title ^(scratch-u)$
windowrule = workspace special:scratch_i silent, match:initial_title ^(scratch-i)$
windowrule = workspace special:scratch_l silent, match:initial_title ^(scratch-l)$
windowrule = workspace special:scratch_h silent, match:initial_title ^(scratch-h)$
windowrule = workspace special:scratch_m silent, match:initial_title ^(scratch-m)$
