# Запуск демона
exec-once = sleep 10 && pypr

# --- ГЛАВНОЕ ПРАВИЛО ---
# Используем initialTitle, так как Ghostty игнорирует --class
windowrulev2 = float, initialTitle:^(scratch-[uilhm])$
windowrulev2 = center, initialTitle:^(scratch-[uilhm])$

# --- ПРИВЯЗКА К WORKSPACE ---
# Тоже используем initialTitle для надежности
windowrulev2 = workspace special:scratch_u silent, initialTitle:^(scratch-u)$
windowrulev2 = workspace special:scratch_i silent, initialTitle:^(scratch-i)$
windowrulev2 = workspace special:scratch_l silent, initialTitle:^(scratch-l)$
windowrulev2 = workspace special:scratch_h silent, initialTitle:^(scratch-h)$
windowrulev2 = workspace special:scratch_m silent, initialTitle:^(scratch-m)$
