# Запуск демона
exec-once = sleep 3 && pypr

# --- ПРАВИЛА (ВАЖНО) ---

# 1. Заставляем окно плавать по initialTitle (так как class не работает)
windowrulev2 = float, initialTitle:^(scratch-yazi)$

# 2. Отправляем его под управление pyprland
windowrulev2 = workspace special:scratch_yazi silent, initialTitle:^(scratch-yazi)$

# 3. Центрируем (опционально, но красиво)
windowrulev2 = center, initialTitle:^(scratch-yazi)$

# --- БИНДИНГИ ---
bind = $mainMod, Y, exec, pypr toggle yazi
